### ISSUE TITLE
Issue with running musicsync --spotify-apicode

### ISSUE THREAD

**Issue by wdmnn** [maximilianvoss/spotify-toniebox-sync#10]
I created  a Spotify clientID, clientSecret and set the redirectUri, built the project and tried to run _musicsync --spotify-apicode_ as per the documentation.

Unfortunately it's not working, output is:

```
~/spotify-toniebox-sync/package/target/output$ sudo ./musicsync --spotify-apicode
Usage: spotify-toniebox-sync.jar [--daemon | --input INPUT --output OUTPUT]
--daemon
		Run in daemon mode to sync periodically all lists in the properties file
--input INPUT
		Define an input source for a one-time run
--output OUTPUT
		Define an output destination for a one-time run

Input Plugins:

Output Plugins:
```

Honestly I have no idea about Java but to me it looks like the plugins are not "registered" and therefor the --spotify-apicode command is unknown?!

**Comment by erikp152** [comment]
@wdmnn If you've generated the URI for input and output-values already as described, you have to insert these tags as described in the documentation, because they are only placeholders with "INPUT" and "OUTPUT". If you have configured the properties in the correct way, you can start the daemon with "java -jar musicsync-application-2.0-SNAPSHOT.jar --daemon &", as well. The *.jar-file must have your jar-file-name.

You can see how the properties should look like in https://github.com/maximilianvoss/spotify-toniebox-sync/blob/v2.0/application/src/main/resources/musicsync.properties.

**Comment by wdmnn** [comment]
properties file is configured for spotify as well as toniebox, mapping is entered. Only thing that's missing is the spotify refreshToken.

```
# Spotify Properties
spotify.clientId=177a869d106xxxxxxxxxxxf7c5a43e1
spotify.clientSecret=cb2c68db2740xxxxxxxxxxxxx242ebd9
spotify.redirectUri=https://xxxxxxx.de/spotify-redirect
spotify.refreshToken=
spotify.cachePath=/user/toniesync/cache/

# Toniebox properties
toniebox.username=family@xxxxxxxxxxx.de
toniebox.password=xxxxxxxxxxxxxx
toniebox.trackname="%d - %a - %n"

# Mapping for Daemon mode
# Values are an array list, X starts at 0
# Example:
# mapping[X]=<InputPlugin>:<InputPluginUri>;<OutpoutPlugin>:<OutputPluginUri>

mapping[0]=spotify:playlist:37i9dQZF1DX7vUfXXazMs3;toniebox:b7a0efcf-xxxx-xxxx-a9c6-8e05b88bc08e:C16Fxxxxxxxx304E0
```

**Comment by maximilianvoss** [comment]
Have you tried following the documentation around getting the refreshToken?
See here: https://github.com/maximilianvoss/spotify-toniebox-sync/blob/v2.0/plugins/input/spotify/README.md
