### ISSUE TITLE
Running Spotify Toniebox Sync on your local environment/server

### ISSUE THREAD

**Issue by frickec7** [maximilianvoss/spotify-toniebox-sync#7]
Hey Guys,
i'm a little bit at a loss because of want to run this tooling on a windows 10 environment. Is it possible or do we need a linux based os? If you have some advice for a windows setting, let me know. Best regards!

**Comment by udovic2100** [comment]
I tried to do it on mac os but got problems with the underlying stream recorder perl script because that uses functions that are only available under linux. So i set up a linux virtual machine and so far the stream recorder and the tonie upload work independently. I haven’t figured out so far what the problem with the overall java tool is for me.

**Comment by maximilianvoss** [comment]
Hi, 
only Linux is supported. Sorry for inconveniences.
Best,
Max
